### ISSUE TITLE
CPAN Pull request Challenge

### ISSUE THREAD

**Issue by SparkeyG** [aferreira/cpan-Carp-Always#4]
Adriano,
I've joined the cpan pull request challenge and was given your module. If it is okay with you, I'd like to help look into the active bugs on rt.perl.org. I'll also like to improve test coverage.

**Comment by aferreira** [comment]
Hello, Shawn. I gave you access to the repo. Thanks!

**Comment by SparkeyG** [comment]
I've merged in two small changes. The first is to close the test bug the
second is to up the Kwalitee score of the module. Please review. Thank you
for letting me help.


shawn.c.carroll@gmail.com
Software Engineer
Soccer Referee
