### ISSUE TITLE
Add Devel::Confess to See Also

### ISSUE THREAD

**Issue by haarg** [aferreira/cpan-Carp-Always#7]
Devel::Confess began as PR#2, adding stack traces to objects.  Since then, it has expanded to add the functions of Carp::Source::Always, Carp::Always::Color, and a number of other things.

**Comment by aferreira** [comment]
Fixed with 0.14 release: https://metacpan.org/pod/release/FERREIRA/Carp-Always-0.14/lib/Carp/Always.pm#SEE-ALSO
