### ISSUE TITLE
Is there any value in being able to choose between shortmess & longmess ?

### ISSUE THREAD

**Issue by DannyThomas** [aferreira/cpan-Carp-Always#9]
I usually prefer shortmess rather than the extended stacktrace

If implemented, I'm ambivalent whether the selection happens during import, or via an exported variable.

cheers,
Danny Thomas

**Comment by aferreira** [comment]
To be noisy with stacktraces is the point of [Carp::Always](https://metacpan.org/pod/Carp::Always#NAME). It is intended for debugging where the more information the better. So I would say that I see no value on choosing between shortmess & longmess.

You may achieve what you want by inheriting from `Carp::Always` and redefining `_warn` and `_die` – something like (which I haven't tested):
```perl
package Carp::Always::ButQuieter;
use base 'Carp::Always';
sub _warn { warn &Carp::shortmess }
sub _die { die ref $_[0] ? @_ : &Carp::shortmess }
1;
```

**Comment by DannyThomas** [comment]
sure, for production the more info the better to diagnose an unexpected situation
but during development, I prefer the short form.
Allowing a choice would be simple, but I guess there's little point if other people have not requested it.
